name: Build and test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install build and test deps
        run: |
          sudo apt install -y build-essential python-is-python3 python3-pip
          pip install pytest
      - name: Build
        run: make
      - name: Run tests
        run: make test
